name: Reusable Build and Push

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
        description: 'Name of the Docker image'
      image_tag:
        required: true
        type: string
        description: 'Tag of the Docker image'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: docker/setup-buildx-action@v3
      
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase Repository Owner
        run: |
          echo "REPO_OWNER=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.REPO_OWNER }}/${{ inputs.image_name }}:${{ inputs.image_tag }}
            ghcr.io/${{ env.REPO_OWNER }}/${{ inputs.image_name }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        continue-on-error: true
        with:
          image-ref: 'ghcr.io/${{ env.REPO_OWNER }}/${{ inputs.image_name }}:${{ inputs.image_tag }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Generate SBOM with Syft
        if: always()
        uses: anchore/sbom-action@v0
        with:
          image: 'ghcr.io/${{ env.REPO_OWNER }}/${{ inputs.image_name }}:${{ inputs.image_tag }}'
          format: 'spdx-json'
          output-file: 'sbom.spdx.json'

      - name: Upload SBOM as Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sbom-report
          path: sbom.spdx.json
